"""Constants for the europa_1400_tools package."""

from enum import Enum, IntEnum
from pathlib import Path

# Game Directories and Files

DATA_DIR = "Data"
A_GEB_DAT = "A_Geb.dat"
A_OBJ_DAT = "A_Obj.dat"

GFX_DIR = "GFX"
BMP_DIR = "Bmp"
GROUNDPLANS_DIR = "GroundPlans"
MAPS_DIR = "Maps"
CHARACTER_NAMES_DAT = "character_names.dat"
GILDE_ADD_ON_GERMAN_GFX = "Gilde_add_on_german.gfx"
NO_COMPRESSION_INI = "no_compression.ini"

MOVIE_DIR = "Movie"
MSX_DIR = "msx"

RESOURCES_DIR = "Resources"
ANIMATIONS_BIN = "animations.bin"
FORMS_BIN0 = "forms.bin0"
GROUPS_BIN = "groups.bin"
OBJECTS_BIN = "objects.bin"
SCENES_BIN = "scenes.bin"
SCRIPTS_BIN = "scripts.bin"
SCRIPTS_BIN1 = "scripts.bin1"
TEXBIN_GERMAN_BIN = "textbin_german.bin"
TEXTURES_BIN = "textures.bin"

SERVER_DIR = "server"

SFX_DIR = "sfx"

AI_METHOD_ADDON_INI = "ai_method_addon.ini"
ALCHEMY_DATA_INI = "alchemy_data.ini"
DIE_GILDE_ADD_ON_TEXT_DEF = "die_gilde_add_on_text.def"
GAME_INI = "game.ini"
GILDEGOLD_EXE = "GildeGold.exe"
GILDEGOLD_TL_EXE = "GildeGold_TL.exe"
INCLUDE_SFX_INI = "include_sfx.ini"
MOVEAHEAD_DLL = "moveahead.dll"

# Directory and File Categories

BIN_FILES = [
    ANIMATIONS_BIN,
    FORMS_BIN0,
    GROUPS_BIN,
    OBJECTS_BIN,
    SCENES_BIN,
    SCRIPTS_BIN,
    SCRIPTS_BIN1,
    TEXBIN_GERMAN_BIN,
    TEXTURES_BIN,
]

# Output Directories and Files

EXTRACTED_DIR = "extracted"
DECODED_DIR = "decoded"
CONVERTED_DIR = "converted"
OUTPUT_AGEB_DIR = "ageb"
OUTPUT_AOBJ_DIR = "aobj"
OUTPUT_SFX_DIR = "sfx"
OUTPUT_GFX_DIR = "gfx"
OUTPUT_GROUPS_DIR = "groups"
OUTPUT_ANIMATIONS_DIR = "animations"
OUTPUT_SCENES_DIR = "scenes"
OUTPUT_OBJECTS_DIR = "objects"

# File Extensions

BGF_EXTENSION = ".bgf"
OBJ_EXTENSION = ".obj"
MTL_EXTENSION = ".mtl"
BAF_EXTENSION = ".baf"
GLTF_EXTENSION = ".gltf"
GLB_EXTENSION = ".glb"
PNG_EXTENSION = ".png"
INI_EXTENSION = ".ini"
SBF_EXTENSION = ".sbf"
PICKLE_EXTENSION = ".pickle"
WAV_EXTENSION = ".wav"
MP3_EXTENSION = ".mp3"
GFX_EXTENSION = ".gfx"
LFS_EXTENSION = ".lfs"
OGR_EXTENSION = ".ogr"
JSON_EXTENSION = ".json"
OAM_EXTENSION = ".oam"
ED3_EXTENSION = ".ed3"
TXS_EXTENSION = ".txs"

# Construct


class SoundbankType(IntEnum):
    """Soundbank types."""

    SINGLE = 1
    MULTI = 2


class SoundType(IntEnum):
    """Sbf types."""

    WAV = 1
    MP3 = 2


# Converter


class TargetAudioFormat(Enum):
    """Target audio formats."""

    WAV = "wav"
    MP3 = "mp3"


class TargetObjectFormat(Enum):
    """Target object formats."""

    WAVEFRONT = "wavefront"
    GLTF = "gltf"
    GLTF_STATIC = "gltf_static"


class OgrElementType(Enum):
    """Ogr element types."""

    OBJECT = "object"
    LIGHT = "light"
    DUMMY = "dummy"


BGF_DIR = "bgf"
OBJ_DIR = "obj"
TEX_DIR = "tex"
GLTF_DIR = "gltf"
BAF_DIR = "baf"

OBJECTS_STRING_ENCODING = "latin-1"

MODELS_REDUCED_FOOTER_FILES = [
    "ob_DREIFACHGALGEN.bgf",
    "ob_DREIFACKREUZ.bgf",
    "ob_EXEKUTIONSKANONESTOPFER.bgf",
]

BGF_EXCLUDE: list[Path] = []
BAF_EXCLUDE: list[Path] = []

WAVEFRONT_ENCODING = "utf-8"

BAF_INI_FILE_SECTION = "4HEAD Studios Animation-Settings"
BAF_INI_FILE_NUM_KEYS = "NumKeys"
BAF_INI_FILE_KEYS = "Keys"
BAF_INI_FILE_LOOP_IN = "LoopIn"
BAF_INI_FILE_LOOP_OUT = "LoopOut"


DEFAULT_OUTPUT_PATH = Path("output")


BAF_TO_BGFS = {
    "BAUM/faellen_BUCHE_01.baf": [],
    "BAUM/faellen_BUCHE_02.baf": [],
    "BAUM/faellen_BUCHE_03.baf": [],
    "BAUM/faellen_BUCHE_04.baf": [],
    "BAUM/faellen_EICHE_01.baf": [],
    "BAUM/faellen_EICHE_02.baf": [],
    "BAUM/faellen_EICHE_03.baf": [],
    "BAUM/faellen_EICHE_04.baf": [],
    "BAUM/faellen_TANNE_01.baf": [],
    "BAUM/faellen_TANNE_02.baf": [],
    "BAUM/faellen_TANNE_03.baf": [],
    "BAUM/faellen_TANNE_04.baf": [],
    "BAUM/flirren_BUCHE.baf": [],
    "BAUM/flirren_EICHE.baf": [],
    "BAUM/flirren_LAUBKRONE.baf": [],
    "BAUM/hack_BUCHE.baf": [],
    "BAUM/hack_TANNE_KRONE.baf": [],
    "BAUM/wiegen_TANNE_01.baf": [],
    "BAUM/wiegen_TANNE_02.baf": [],
    "BAUM/wiegen_TANNE_03.baf": [],
    "BAUM/wiegen_TANNE_04.baf": [],
    "BAUM/wiegen_TANNE_KRONE.baf": [],
    "BAUM/windhauch_LAUBKRONE01.baf": [],
    "BAUM/zittern_BUCHE.baf": [],
    "BAUM/zittern_EICHE.baf": [],
    "BAUM/zittern_TANNE.baf": [],
    "Buch/Buch_schliessen.baf": [],
    "Buch/Buch_schliessen_s.baf": [],
    "Buch/Buch_vorblaettern.baf": [],
    "Buch/Buch_vorblaettern_s.baf": [],
    "Buch/Buch_zurueckblaettern.baf": [],
    "Buch/Buch_zurueckblaettern_s.baf": [],
    "Character/BAER/Aufrichten_BAER.baf": [],
    "Character/BAER/Hinsetzen_BAER.baf": [],
    "Character/BAER/Laufen_BAER.baf": [],
    "Character/BAER/Tanzen_BAER.baf": [],
    "Character/BAER/Tanzen_im_Kreis_BAER.baf": [],
    "Character/BAER/warten_BAER.baf": [],
    "Character/BAER/warten_noise_BAER.baf": [],
    "Character/DICKER/abstimmung/sitzung1_DICKER.baf": [],
    "Character/DICKER/abstimmung/sitzung2_DICKER.baf": [],
    "Character/DICKER/abstimmung/sitzung3_DICKER.baf": [],
    "Character/DICKER/abstimmung/sitzung4_DICKER.baf": [],
    "Character/DICKER/abstimmung/sitzung5_DICKER.baf": [],
    "Character/DICKER/ARBEIT/am_tisch_schreiben_DICKER.baf": [],
    "Character/DICKER/ARBEIT/baumfaellen_DICKER.baf": [],
    "Character/DICKER/ARBEIT/hacken_DICKER.baf": [],
    "Character/DICKER/ARBEIT/hebel_ziehen_DICKER.baf": [],
    "Character/DICKER/ARBEIT/hobeln_DICKER.baf": [],
    "Character/DICKER/ARBEIT/meisseln_DICKER.baf": [],
    "Character/DICKER/ARBEIT/metall_erhitzen_DICKER.baf": [],
    "Character/DICKER/ARBEIT/mist_schaufeln_DICKER.baf": [],
    "Character/DICKER/ARBEIT/muenz_praegung_DICKER.baf": [],
    "Character/DICKER/ARBEIT/naehen_DICKER.baf": [],
    "Character/DICKER/ARBEIT/neufegen2_DICKER.baf": [],
    "Character/DICKER/ARBEIT/saegen_DICKER.baf": [],
    "Character/DICKER/ARBEIT/schmieden_DICKER.baf": [],
    "Character/DICKER/ARBEIT/schoepfen_DICKER.baf": [],
    "Character/DICKER/ARBEIT/schreiben_DICKER.baf": [],
    "Character/DICKER/ARBEIT/schweissab_DICKER.baf": [],
    "Character/DICKER/ARBEIT/seil_ziehen_DICKER.baf": [],
    "Character/DICKER/ARBEIT/umruehren_auftisch_DICKER.baf": [],
    "Character/DICKER/ARBEIT/umruehren_DICKER.baf": [],
    "Character/DICKER/ARBEIT/zapfen_DICKER.baf": [],
    "Character/DICKER/Bewegung/dreh_45_links_DICKER.baf": [],
    "Character/DICKER/Bewegung/dreh_45_rechts_DICKER.baf": [],
    "Character/DICKER/Bewegung/dreh_90_links_DICKER.baf": [],
    "Character/DICKER/Bewegung/dreh_90_rechts_DICKER.baf": [],
    "Character/DICKER/Bewegung/gebueckt_gehen_DICKER.baf": [],
    "Character/DICKER/Bewegung/gehen_DICKER.baf": [],
    "Character/DICKER/Bewegung/Karren_ziehen_DICKER.baf": [],
    "Character/DICKER/Bewegung/karren_ziehen__DICKER.baf": [],
    "Character/DICKER/Bewegung/leitersteigen_DICKER.baf": [],
    "Character/DICKER/Bewegung/springen_DICKER.baf": [],
    "Character/DICKER/Bewegung/step_DICKER.baf": [],
    "Character/DICKER/Bewegung/zu_Boden_sinken_DICKER.baf": [],
    "Character/DICKER/GESTIK/abfaellig_DICKER.baf": [],
    "Character/DICKER/GESTIK/anpreisen_DICKER.baf": [],
    "Character/DICKER/GESTIK/armsehen_DICKER.baf": [],
    "Character/DICKER/GESTIK/bauch_reiben_DICKER.baf": [],
    "Character/DICKER/GESTIK/bein_kratzen_DICKER.baf": [],
    "Character/DICKER/GESTIK/beschwoeren_DICKER.baf": [],
    "Character/DICKER/GESTIK/durch_haar_fahr_DICKER.baf": [],
    "Character/DICKER/GESTIK/gespraech1_DICKER.baf": [],
    "Character/DICKER/GESTIK/gespraech5_DICKER.baf": [],
    "Character/DICKER/GESTIK/gespraech6_DICKER.baf": [],
    "Character/DICKER/GESTIK/haende_reiben_DICKER.baf": [],
    "Character/DICKER/GESTIK/herranwinken_DICKER.baf": [],
    "Character/DICKER/GESTIK/jubeln_DICKER.baf": [],
    "Character/DICKER/GESTIK/kinn_kratzen_DICKER.baf": [],
    "Character/DICKER/GESTIK/klatschen_DICKER.baf": [],
    "Character/DICKER/GESTIK/kopf_kratzen_DICKER.baf": [],
    "Character/DICKER/GESTIK/kopf_nicken_DICKER.baf": [],
    "Character/DICKER/GESTIK/kopf_schraeg_links_DICKER.baf": [],
    "Character/DICKER/GESTIK/kopf_schraeg_rechts_DICKER.baf": [],
    "Character/DICKER/GESTIK/kopf_schuetteln_DICKER.baf": [],
    "Character/DICKER/GESTIK/manipulieren_hockend_DICKER.baf": [],
    "Character/DICKER/GESTIK/manipulieren_stehend_DICKER.baf": [],
    "Character/DICKER/GESTIK/mit_faust_droh_DICKER.baf": [],
    "Character/DICKER/GESTIK/nach_unten_sehen_DICKER.baf": [],
    "Character/DICKER/GESTIK/segnen_DICKER.baf": [],
    "Character/DICKER/GESTIK/steh_noise61_DICKER.baf": [],
    "Character/DICKER/GESTIK/steh_noise7_DICKER.baf": [],
    "Character/DICKER/GESTIK/steh_noise8_DICKER.baf": [],
    "Character/DICKER/GESTIK/steh_noise9_DICKER.baf": [],
    "Character/DICKER/GESTIK/um_hand_anhalten_DICKER.baf": [],
    "Character/DICKER/GESTIK/verbeugen_DICKER.baf": [],
    "Character/DICKER/GESTIK/zeigen_DICKER.baf": [],
    "Character/DICKER/GESTIK/zum_mund_DICKER.baf": [],
    "Character/DICKER/Kampf/arm_greifen_DICKER.baf": [],
    "Character/DICKER/Kampf/aufstehen_DICKER.baf": [],
    "Character/DICKER/Kampf/ausweichen_hinten_DICKER.baf": [],
    "Character/DICKER/Kampf/ausweichen_seite_DICKER.baf": [],
    "Character/DICKER/Kampf/bauch_greifen_DICKER.baf": [],
    "Character/DICKER/Kampf/boxen_DICKER.baf": [],
    "Character/DICKER/Kampf/budspencerhieb_DICKER.baf": [],
    "Character/DICKER/Kampf/ducken_DICKER.baf": [],
    "Character/DICKER/Kampf/hieb_abwehr_DICKER.baf": [],
    "Character/DICKER/Kampf/hieb_DICKER.baf": [],
    "Character/DICKER/Kampf/priester_DICKER.baf": [],
    "Character/DICKER/Kampf/schiessen_armbrust_DICKER.baf": [],
    "Character/DICKER/Kampf/schiessen_pistole_DICKER.baf": [],
    "Character/DICKER/Kampf/schlagen1_DICKER.baf": [],
    "Character/DICKER/Kampf/schlagen2_DICKER.baf": [],
    "Character/DICKER/Kampf/schlagen3_DICKER.baf": [],
    "Character/DICKER/Kampf/schulter_anrempeln_DICKER.baf": [],
    "Character/DICKER/Kampf/stechen_DICKER.baf": [],
    "Character/DICKER/Kampf/sterben_DICKER.baf": [],
    "Character/DICKER/Kampf/stich_abwehr_DICKER.baf": [],
    "Character/DICKER/Kampf/stich_ausweichen_DICKER.baf": [],
    "Character/DICKER/Kampf/stich_DICKER.baf": [],
    "Character/DICKER/Kampf/streich_DICKER.baf": [],
    "Character/DICKER/Kampf/taumeln_DICKER.baf": [],
    "Character/DICKER/Kampf/todumfallen_DICKER.baf": [],
    "Character/DICKER/Kampf/wegstossen_DICKER.baf": [],
    "Character/DICKER/Kampf/werfen_DICKER.baf": [],
    "Character/DICKER/Kampf/zu_boden_sinken_DICKER.baf": [],
    "Character/DICKER/Master_Dicker.baf": [],
    "Character/DICKER/SITZEND/aufstehen_DICKER.baf": [],
    "Character/DICKER/SITZEND/hinsetzen_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitzgespraech2_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitzgespraech3_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_ja_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_kopfdreh_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_kopfsenk_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_manipulieren_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_nein_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_newnoise_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_noise1_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_noise2_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_noise3_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_noise4_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_reden_aufgeregt_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_reden_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_schreiben_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_still_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_trinken_DICKER.baf": [],
    "Character/DICKER/SITZEND/sitz_umschau_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/auf_ruecken_schwing_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/auf_tisch_legen_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/auskippen_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/betrunken_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/einhaendig_vom_boden_nehmen_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/einhand_vom_tisch_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/fallenlassen_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/gegenstand_schuetteln_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/gegenstand_schuetteln_zweihaendig_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/in_andere_hand_geben_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/in_guertel_steck_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/in_tasche_steck_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/laterne_anzuenden_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/meckern_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/niederkniehen_ehre_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/niederkniehen_tod_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/runterbeug_sucht_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/runterbeug_such_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/scheiterhaufen_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/singen_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/taumelnd_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/wuerfel_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/zweihand_vom_boden_aufnehmen_DICKER.baf": [],
    "Character/DICKER/SPEZIAL/zweihand_vom_tisch_DICKER.baf": [],
    "Character/DICKER/Stand_still_DICKER.baf": [],
    "Character/DICKER/STEHEN/stehen_newnoise_DICKER.baf": [],
    "Character/FRAU/abstimmung/sitzung1_FRAU.baf": [],
    "Character/FRAU/abstimmung/sitzung2_FRAU.baf": [],
    "Character/FRAU/abstimmung/sitzung3_FRAU.baf": [],
    "Character/FRAU/abstimmung/sitzung4_FRAU.baf": [],
    "Character/FRAU/abstimmung/sitzung5_FRAU.baf": [],
    "Character/FRAU/ARBEIT/am_tisch_schreiben_FRAU.baf": [],
    "Character/FRAU/ARBEIT/baumfaellen_FRAU.baf": [],
    "Character/FRAU/ARBEIT/hacken_FRAU.baf": [],
    "Character/FRAU/ARBEIT/hebel_ziehen_FRAU.baf": [],
    "Character/FRAU/ARBEIT/hobeln_FRAU.baf": [],
    "Character/FRAU/ARBEIT/meisseln_FRAU.baf": [],
    "Character/FRAU/ARBEIT/metall_erhitzen_FRAU.baf": [],
    "Character/FRAU/ARBEIT/mist_schaufeln_FRAU.baf": [],
    "Character/FRAU/ARBEIT/muenz_praegung_FRAU.baf": [],
    "Character/FRAU/ARBEIT/naehen_FRAU.baf": [],
    "Character/FRAU/ARBEIT/neufegen2_FRAU.baf": [],
    "Character/FRAU/ARBEIT/saegen_FRAU.baf": [],
    "Character/FRAU/ARBEIT/schmieden_FRAU.baf": [],
    "Character/FRAU/ARBEIT/schoepfen_FRAU.baf": [],
    "Character/FRAU/ARBEIT/schreiben_FRAU.baf": [],
    "Character/FRAU/ARBEIT/schweissab_FRAU.baf": [],
    "Character/FRAU/ARBEIT/seil_ziehen_FRAU.baf": [],
    "Character/FRAU/ARBEIT/umruehren_auftisch_FRAU.baf": [],
    "Character/FRAU/ARBEIT/umruehren_FRAU.baf": [],
    "Character/FRAU/ARBEIT/zapfen_FRAU.baf": [],
    "Character/FRAU/Bewegung/dreh_45_links_FRAU.baf": [],
    "Character/FRAU/Bewegung/dreh_45_rechts_FRAU.baf": [],
    "Character/FRAU/Bewegung/dreh_90_links_FRAU.baf": [],
    "Character/FRAU/Bewegung/dreh_90_rechts_FRAU.baf": [],
    "Character/FRAU/Bewegung/gebueckt_gehen_FRAU.baf": [],
    "Character/FRAU/Bewegung/gehen_FRAU.baf": [],
    "Character/FRAU/Bewegung/karren_ziehen_FRAU.baf": [],
    "Character/FRAU/Bewegung/leitersteigen_FRAU.baf": [],
    "Character/FRAU/Bewegung/linksdrehen45_FRAU.baf": [],
    "Character/FRAU/Bewegung/linksdrehen90_FRAU.baf": [],
    "Character/FRAU/Bewegung/rechtsdrehen45_FRAU.baf": [],
    "Character/FRAU/Bewegung/rechtsdrehen90_FRAU.baf": [],
    "Character/FRAU/Bewegung/schritt_FRAU.baf": [],
    "Character/FRAU/Bewegung/springen_FRAU.baf": [],
    "Character/FRAU/Bewegung/step_FRAU.baf": [],
    "Character/FRAU/Bewegung/zu_boden_sinken_FRAU.baf": [],
    "Character/FRAU/Gestik/abfaellig_FRAU.baf": [],
    "Character/FRAU/Gestik/anpreisen_FRAU.baf": [],
    "Character/FRAU/Gestik/armsehen_FRAU.baf": [],
    "Character/FRAU/Gestik/bauch_reiben_FRAU.baf": [],
    "Character/FRAU/Gestik/bein_kratzen_FRAU.baf": [],
    "Character/FRAU/Gestik/beschwoeren_FRAU.baf": [],
    "Character/FRAU/Gestik/durch_haar_fahr_FRAU.baf": [],
    "Character/FRAU/Gestik/gespraech1_FRAU.baf": [],
    "Character/FRAU/Gestik/gespraech5_FRAU.baf": [],
    "Character/FRAU/Gestik/gespraech6_FRAU.baf": [],
    "Character/FRAU/Gestik/haende_reiben_FRAU.baf": [],
    "Character/FRAU/Gestik/herranwinken_FRAU.baf": [],
    "Character/FRAU/Gestik/jubeln_FRAU.baf": [],
    "Character/FRAU/Gestik/kinn_kratzen_FRAU.baf": [],
    "Character/FRAU/Gestik/klatschen_FRAU.baf": [],
    "Character/FRAU/Gestik/kopf_kratzen_FRAU.baf": [],
    "Character/FRAU/Gestik/kopf_nicken_FRAU.baf": [],
    "Character/FRAU/Gestik/kopf_schraeg_links_FRAU.baf": [],
    "Character/FRAU/Gestik/kopf_schraeg_rechts_FRAU.baf": [],
    "Character/FRAU/Gestik/kopf_schuetteln_FRAU.baf": [],
    "Character/FRAU/Gestik/manipulieren_hockend_FRAU.baf": [],
    "Character/FRAU/Gestik/manipulieren_stehend_FRAU.baf": [],
    "Character/FRAU/Gestik/mit_faust_droh_FRAU.baf": [],
    "Character/FRAU/Gestik/nach_unten_sehen_FRAU.baf": [],
    "Character/FRAU/Gestik/segnen_FRAU.baf": [],
    "Character/FRAU/Gestik/steh_noise61_FRAU.baf": [],
    "Character/FRAU/Gestik/steh_noise7_FRAU.baf": [],
    "Character/FRAU/Gestik/steh_noise8_FRAU.baf": [],
    "Character/FRAU/Gestik/steh_noise9_FRAU.baf": [],
    "Character/FRAU/Gestik/um_hand_anhalten_FRAU.baf": [],
    "Character/FRAU/Gestik/verbeugen_FRAU.baf": [],
    "Character/FRAU/Gestik/zeigen_FRAU.baf": [],
    "Character/FRAU/Gestik/zeigen_zeigen_FRAU.baf": [],
    "Character/FRAU/Gestik/zum_mund_FRAU.baf": [],
    "Character/FRAU/KAMPF/arm_greifen_FRAU.baf": [],
    "Character/FRAU/KAMPF/aufrichten_FRAU.baf": [],
    "Character/FRAU/KAMPF/aufstehen_FRAU.baf": [],
    "Character/FRAU/KAMPF/ausweichen_hinten_FRAU.baf": [],
    "Character/FRAU/KAMPF/ausweichen_seite_FRAU.baf": [],
    "Character/FRAU/KAMPF/bauch_greifen_FRAU.baf": [],
    "Character/FRAU/KAMPF/boxen_FRAU.baf": [],
    "Character/FRAU/KAMPF/budspencerhieb_FRAU.baf": [],
    "Character/FRAU/KAMPF/ducken_FRAU.baf": [],
    "Character/FRAU/KAMPF/hieb_abwehr_FRAU.baf": [],
    "Character/FRAU/KAMPF/hieb_FRAU.baf": [],
    "Character/FRAU/KAMPF/priester_FRAU.baf": [],
    "Character/FRAU/KAMPF/schiessen_armbrust_FRAU.baf": [],
    "Character/FRAU/KAMPF/schiessen_pistole_FRAU.baf": [],
    "Character/FRAU/KAMPF/schlagen1_FRAU.baf": [],
    "Character/FRAU/KAMPF/schlagen2_FRAU.baf": [],
    "Character/FRAU/KAMPF/schlagen3_FRAU.baf": [],
    "Character/FRAU/KAMPF/schulter_anrempeln_FRAU.baf": [],
    "Character/FRAU/KAMPF/stechen_FRAU.baf": [],
    "Character/FRAU/KAMPF/sterben_FRAU.baf": [],
    "Character/FRAU/KAMPF/stich_abwehr_FRAU.baf": [],
    "Character/FRAU/KAMPF/stich_ausweichen_FRAU.baf": [],
    "Character/FRAU/KAMPF/stich_FRAU.baf": [],
    "Character/FRAU/KAMPF/streich_FRAU.baf": [],
    "Character/FRAU/KAMPF/taumeln_FRAU.baf": [],
    "Character/FRAU/KAMPF/todumfallen_FRAU.baf": [],
    "Character/FRAU/KAMPF/wegstossen_FRAU.baf": [],
    "Character/FRAU/KAMPF/werfen_FRAU.baf": [],
    "Character/FRAU/KAMPF/zu_boden_sinken_FRAU.baf": [],
    "Character/FRAU/SITZEND/aufstehen_FRAU.baf": [],
    "Character/FRAU/SITZEND/hinsetzen_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitzgespraech2_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitzgespraech3_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_ja_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_kopfdreh_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_kopfsenk_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_manipulieren_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_nein_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_newnoise_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_noise1_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_noise2_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_noise3_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_noise4_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_reden_aufgeregt_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_reden_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_schreiben_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_still_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_trinken_FRAU.baf": [],
    "Character/FRAU/SITZEND/sitz_umschau_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/auf_ruecken_schwing_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/auf_tisch_legen_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/auskippen_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/einhaendig_vom_boden_nehmen_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/einhand_vom_tisch_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/fallenlassen_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/gegenstand_schuetteln_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/gegenstand_schuetteln_zweihaendig_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/in_andere_hand_geben_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/in_guertel_steck_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/in_tasche_steck_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/laterne_anzuenden_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/meckern_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/niederkniehen_ehre_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/niederkniehen_tod_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/runterbeug_sucht_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/runterbeug_such_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/scheiterhaufen_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/singen_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/wuerfel_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/zweihand_vom_boden_aufnehmen_FRAU.baf": [],
    "Character/FRAU/SPEZIAL/zweihand_vom_tisch_FRAU.baf": [],
    "Character/FRAU/Stand_still_FRAU.baf": [],
    "Character/FRAU/STEHEN/stehen_newnoise_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/anfeuern_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/handstand2_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/handstand_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/lachen_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/lange_winken_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/lang_winken_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/posieren_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/ruecksalto2_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/ruecksalto_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/stehend_beschwoeren_FRAU.baf": [],
    "Character/FRAU/ZIRKUS/tief_verbeugen_FRAU.baf": [],
    "Character/FRAU2/Bewegung/dreh_45_links_FRAU2.baf": [],
    "Character/FRAU2/Bewegung/dreh_45_rechts_FRAU2.baf": [],
    "Character/FRAU2/Bewegung/dreh_90_links_FRAU2.baf": [],
    "Character/FRAU2/Bewegung/dreh_90_rechts_FRAU2.baf": [],
    "Character/FRAU2/Bewegung/gehen_FRAU2.baf": [],
    "Character/FRAU2/Gestik/beschwoeren_FRAU2.baf": [],
    "Character/FRAU2/Gestik/haende_reiben_FRAU2.baf": [],
    "Character/FRAU2/Gestik/herranwinken_FRAU2.baf": [],
    "Character/FRAU2/Gestik/kopf_nicken_FRAU2.baf": [],
    "Character/FRAU2/Gestik/Manipulieren_stehend_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/aufstehen_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/hinsetzen_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/sitz_manipulieren_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/sitz_newnoise_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/sitz_reden_aufgeregt_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/sitz_reden_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/sitz_schreiben_FRAU2.baf": [],
    "Character/FRAU2/Sitzend/sitz_trinken_FRAU2.baf": [],
    "Character/FRAU2/Stehen/stehen_newnoise_FRAU2.baf": [],
    "Character/FRAU3/Arbeit/Buddeln_FRAU3.baf": [],
    "Character/FRAU3/Arbeit/neufegen2_FRAU3.baf": [],
    "Character/FRAU3/Bewegung/aufstehen_FRAU3.baf": [],
    "Character/FRAU3/Bewegung/dreh_45_links_FRAU3.baf": [],
    "Character/FRAU3/Bewegung/dreh_45_rechts_FRAU3.baf": [],
    "Character/FRAU3/Bewegung/dreh_90_links_FRAU3.baf": [],
    "Character/FRAU3/Bewegung/dreh_90_rechts_FRAU3.baf": [],
    "Character/FRAU3/Bewegung/gehen_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Beschwoeren_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Blume_im_Mund_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Manipulieren_Hockend_FRAU3.baf": [],
    "Character/FRAU3/Gestik/manipulieren_stehend_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Ruelpser_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Schimpfen_FRAU3.baf": [],
    "Character/FRAU3/Gestik/schlaege_FRAU3.baf": [],
    "Character/FRAU3/Gestik/schlaege_liegen_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Sterben_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Umkippen_FRAU3.baf": [],
    "Character/FRAU3/Gestik/Verbeugen_FRAU3.baf": [],
    "Character/FRAU3/Spezial/auferstehung_FRAU3.baf": [],
    "Character/FRAU3/Spezial/Elektroschock_FRAU3.baf": [],
    "Character/FRAU3/Spezial/Stehlen_FRAU3.baf": [],
    "Character/FRAU3/Stehen/stehen_FRAU3.baf": [],
    "Character/FRAU3/Stehen/stehen_newnoise_FRAU3.baf": [],
    "Character/Huhn/Bewegung/flattern_HUHN.baf": [],
    "Character/Huhn/Bewegung/fressen_HUHN.baf": [],
    "Character/Huhn/Bewegung/gehen_HUHN.baf": [],
    "Character/Huhn/Bewegung/stehen_HUHN.baf": [],
    "Character/Hund/Bewegung/bellen_HUND.baf": [],
    "Character/Hund/Bewegung/gehen_HUND.baf": [],
    "Character/Hund/Bewegung/stehen_HUND.baf": [],
    "Character/JUNGE/Bewegung/dreh_45_links_JUNGE.baf": [],
    "Character/JUNGE/Bewegung/dreh_45_rechts_JUNGE.baf": [],
    "Character/JUNGE/Bewegung/dreh_90_links_JUNGE.baf": [],
    "Character/JUNGE/Bewegung/dreh_90_rechts_JUNGE.baf": [],
    "Character/JUNGE/Bewegung/gehen_JUNGE.baf": [],
    "Character/JUNGE/Bewegung/step_JUNGE.baf": [],
    "Character/karren/Bewegung/karren_ziehen_KARREN.baf": [],
    "Character/Katze/Bewegung/gehen_KATZE.baf": [],
    "Character/Katze/Bewegung/stehen_KATZE.baf": [],
    "Character/KREATUR/Arbeit/buddeln_KREATUR.baf": [],
    "Character/KREATUR/Arbeit/neufegen2_KREATUR.baf": [],
    "Character/KREATUR/Bewegung/aufstehen_KREATUR.baf": [],
    "Character/KREATUR/Bewegung/dreh_45_links_KREATUR.baf": [],
    "Character/KREATUR/Bewegung/dreh_45_rechts_KREATUR.baf": [],
    "Character/KREATUR/Bewegung/dreh_90_links_KREATUR.baf": [],
    "Character/KREATUR/Bewegung/dreh_90_rechts_KREATUR.baf": [],
    "Character/KREATUR/Bewegung/gehen_KREATUR.baf": [],
    "Character/KREATUR/Gestik/beschwoeren_KREATUR.baf": [],
    "Character/KREATUR/Gestik/blume_im_mund_KREATUR.baf": [],
    "Character/KREATUR/Gestik/manipulieren_hockend_KREATUR.baf": [],
    "Character/KREATUR/Gestik/manipulieren_stehend_KREATUR.baf": [],
    "Character/KREATUR/Gestik/ruelpser_KREATUR.baf": [],
    "Character/KREATUR/Gestik/schimpfen_KREATUR.baf": [],
    "Character/KREATUR/Gestik/schlaege_KREATUR.baf": [],
    "Character/KREATUR/Gestik/schlaege_liegen_KREATUR.baf": [],
    "Character/KREATUR/Gestik/sterben_KREATUR.baf": [],
    "Character/KREATUR/Gestik/umkippen_KREATUR.baf": [],
    "Character/KREATUR/Gestik/verbeugen_KREATUR.baf": [],
    "Character/KREATUR/Spezial/auferstehung_KREATUR.baf": [],
    "Character/KREATUR/Spezial/Elektroschock_KREATUR.baf": [],
    "Character/KREATUR/Spezial/stehlen_KREATUR.baf": [],
    "Character/KREATUR/STEHEN/stehen_KREATUR.baf": [],
    "Character/KREATUR/STEHEN/stehen_newnoise_KREATUR.baf": [],
    "Character/Kritzelkratz/offizier_SOLDAT_schiessen_pistolealt.baf": [],
    "Character/Kritzelkratz/ratsherr2_KUTTE_gehen.baf": [],
    "Character/Kuh/Bewegung/fressen_KUH.baf": [],
    "Character/Kuh/Bewegung/gehen_KUH.baf": [],
    "Character/Kuh/Bewegung/stehen_KUH.baf": [],
    "Character/KUTTE/abstimmung/sitzung1_KUTTE.baf": [],
    "Character/KUTTE/abstimmung/sitzung2_KUTTE.baf": [],
    "Character/KUTTE/abstimmung/sitzung3_KUTTE.baf": [],
    "Character/KUTTE/abstimmung/sitzung4_KUTTE.baf": [],
    "Character/KUTTE/abstimmung/sitzung5_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/am_tisch_schreiben_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/baumfaellen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/hacken_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/hebel_ziehen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/hobeln_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/meisseln_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/metall_erhitzen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/mist_schaufeln_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/muenz_praegung_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/naehen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/neufegen2_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/predigen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/saegen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/schmieden_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/schoepfen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/schreiben_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/schweissab_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/seil_ziehen_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/umruehren_auftisch_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/umruehren_KUTTE.baf": [],
    "Character/KUTTE/Arbeit/zapfen_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/dreh_45_links_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/dreh_45_rechts_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/dreh_90_links_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/dreh_90_rechts_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/gebueckt_gehen_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/gehen_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/karren_ziehen_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/leitersteigen_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/priester_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/springen_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/step_KUTTE.baf": [],
    "Character/KUTTE/Bewegung/zu_boden_sinken_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/abfaellig_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/anpreisen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/armsehen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/bauch_reiben_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/bein_kratzen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/beschwoeren_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/durch_haar_fahr_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/gespraech1_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/gespraech5_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/gespraech6_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/haende_reiben_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/herranwinken_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/jubeln_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/kinn_kratzen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/klatschen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/kopf_kratzen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/kopf_nicken_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/kopf_schraeg_links_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/kopf_schraeg_links_UTTE.baf": [],
    "Character/KUTTE/GESTIK/kopf_schraeg_rechts_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/kopf_schuetteln.baf": [],
    "Character/KUTTE/GESTIK/kopf_schuetteln_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/manipulieren_hockend_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/manipulieren_stehend_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/mit_faust_droh_,KUTTE.baf": [],
    "Character/KUTTE/GESTIK/mit_faust_droh_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/nach_unten_sehen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/segnen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/steh_noise61_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/steh_noise7_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/steh_noise8_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/steh_noise9_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/um_hand_anhalten_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/verbeugen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/zeigen_KUTTE.baf": [],
    "Character/KUTTE/GESTIK/zum_mund_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/arm_greifen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/aufrichten_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/aufstehen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/ausweichen_hinten_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/ausweichen_seite_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/bauch_greifen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/boxen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/budspencerhieb_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/ducken_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/hieb_abwehr_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/hieb_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/priester_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/schiessen_armbrust_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/schiessen_pistole_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/schlagen1_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/schlagen2_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/schlagen3_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/schulter_anrempeln_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/stechen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/sterben_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/stich_abwehr_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/stich_ausweichen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/stich_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/streich_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/taumeln_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/todumfallen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/wegstossen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/werfen2_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/werfen_KUTTE.baf": [],
    "Character/KUTTE/KAMPF/zu_boden_sinken_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/aufstehen_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/aufstehen_SOLDAT.baf": [],
    "Character/KUTTE/SITZEND/hinsetzen_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzend_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzgespraech1_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzgespraech2_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzgespraech3_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzgespraech4_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzgespraech5_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzgespraech6_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitzgespraech7_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_ja_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_kopfdreh_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_kopfsenk_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_manipulieren_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_nein_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_newnoise_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise1_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise2_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise3_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise4_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise5_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise6_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise7_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_noise8_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_reden_aufgeregt_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_reden_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_schreiben_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_still_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_trinken_KUTTE.baf": [],
    "Character/KUTTE/SITZEND/sitz_umschau_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/auf_ruecken_schwing_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/auf_tisch_legen_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/auskippen_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/einhaendig_vom_boden_nehmen_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/einhand_vom_tisch_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/fallenlassen_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/gegenstand_schuetteln_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/gegenstand_schuetteln_zweihaendig_,KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/gegenstand_schuetteln_zweihaendig_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/in_andere_hand_geben_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/in_guertel_steck_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/in_tasche_steck_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/laterne_anzuenden_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/meckern_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/niederkniehen_ehre_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/niederkniehen_tod_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/runterbeug_sucht_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/runterbeug_such_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/scheiterhaufen_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/singen_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/wuerfel_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/zweihand_vom_boden_aufnehmen_KUTTE.baf": [],
    "Character/KUTTE/SPEZIAL/zweihand_vom_tisch_KUTTE.baf": [],
    "Character/KUTTE/STEHEN/stehen_newnoise_KUTTE.baf": [],
    "Character/KUTTE2/bewegung/dreh_45_links_KUTTE2.baf": [],
    "Character/KUTTE2/bewegung/dreh_45_rechts_KUTTE2.baf": [],
    "Character/KUTTE2/bewegung/dreh_90_links_KUTTE2.baf": [],
    "Character/KUTTE2/bewegung/dreh_90_rechts_KUTTE2.baf": [],
    "Character/KUTTE2/bewegung/gehen_KUTTE2.baf": [],
    "Character/KUTTE2/bewegung/stehen_newnoise_KUTTE2.baf": [],
    "Character/KUTTE2/Gestik/kinn_kratzen_KUTTE2.baf": [],
    "Character/KUTTE2/Gestik/Manipulieren_stehend_KUTTE2.baf": [],
    "Character/MAEDCHEN/Bewegung/dreh_45_links_MAEDCHEN.baf": [],
    "Character/MAEDCHEN/Bewegung/dreh_45_rechts_MAEDCHEN.baf": [],
    "Character/MAEDCHEN/Bewegung/dreh_90_links_MAEDCHEN.baf": [],
    "Character/MAEDCHEN/Bewegung/dreh_90_rechts_MAEDCHEN.baf": [],
    "Character/MAEDCHEN/Bewegung/gehen_MAEDCHEN.baf": [],
    "Character/MAEDCHEN/Bewegung/step_MAEDCHEN.baf": [],
    "Character/MANN/abstimmung/sitzung1_MANN.baf": [],
    "Character/MANN/abstimmung/sitzung2_MANN.baf": [],
    "Character/MANN/abstimmung/sitzung3_MANN.baf": [],
    "Character/MANN/abstimmung/sitzung4_MANN.baf": [],
    "Character/MANN/abstimmung/sitzung5_MANN.baf": [],
    "Character/MANN/ARBEIT/am_tisch_schreiben_MANN.baf": [],
    "Character/MANN/ARBEIT/baumfaellen_MANN.baf": [],
    "Character/MANN/ARBEIT/hacken_MANN.baf": [],
    "Character/MANN/ARBEIT/hebel_ziehen_MANN.baf": [],
    "Character/MANN/ARBEIT/hobeln_MANN.baf": [],
    "Character/MANN/ARBEIT/meisseln_MANN.baf": [],
    "Character/MANN/ARBEIT/metall_erhitzen_MANN.baf": [],
    "Character/MANN/ARBEIT/mist_schaufeln_MANN.baf": [],
    "Character/MANN/ARBEIT/muenz_praegung_MANN.baf": [],
    "Character/MANN/ARBEIT/naehen_MANN.baf": [],
    "Character/MANN/ARBEIT/neufegen2_MANN.baf": [],
    "Character/MANN/ARBEIT/saegen_MANN.baf": [],
    "Character/MANN/ARBEIT/schmieden_MANN.baf": [],
    "Character/MANN/ARBEIT/schoepfen_MANN.baf": [],
    "Character/MANN/ARBEIT/schreiben_MANN.baf": [],
    "Character/MANN/ARBEIT/schweissab_MANN.baf": [],
    "Character/MANN/ARBEIT/seil_ziehen_MANN.baf": [],
    "Character/MANN/ARBEIT/umruehren_auftisch_MANN.baf": [],
    "Character/MANN/ARBEIT/umruehren_MANN.baf": [],
    "Character/MANN/ARBEIT/zapfen_MANN.baf": [],
    "Character/MANN/Bewegung/dreh_45_links_MANN.baf": [],
    "Character/MANN/Bewegung/dreh_45_rechts_MANN.baf": [],
    "Character/MANN/Bewegung/dreh_90_links_MANN.baf": [],
    "Character/MANN/Bewegung/dreh_90_rechts_MANN.baf": [],
    "Character/MANN/Bewegung/gebueckt_gehen_MANN.baf": [],
    "Character/MANN/Bewegung/gehen6_MANN.baf": [],
    "Character/MANN/Bewegung/gehen_MANN.baf": [],
    "Character/MANN/Bewegung/karren_ziehen_MANN.baf": [],
    "Character/MANN/Bewegung/leitersteigen_MANN.baf": [],
    "Character/MANN/Bewegung/manipulieren_hockend_MANN.baf": [],
    "Character/MANN/Bewegung/springen_MANN.baf": [],
    "Character/MANN/Bewegung/step_MANN.baf": [],
    "Character/MANN/Bewegung/zu_boden_sinken_MANN.baf": [],
    "Character/MANN/GESTIK/abfaellig_MANN.baf": [],
    "Character/MANN/GESTIK/anpreisen_MANN.baf": [],
    "Character/MANN/GESTIK/armsehen_MANN.baf": [],
    "Character/MANN/GESTIK/bauch_reiben_MANN.baf": [],
    "Character/MANN/GESTIK/bein_kratzen_MANN.baf": [],
    "Character/MANN/GESTIK/beschwoeren_MANN.baf": [],
    "Character/MANN/GESTIK/durch_haar_fahr_MANN.baf": [],
    "Character/MANN/GESTIK/gespraech1_MANN.baf": [],
    "Character/MANN/GESTIK/gespraech5_MANN.baf": [],
    "Character/MANN/GESTIK/gespraech6_MANN.baf": [],
    "Character/MANN/GESTIK/haende_reiben_MANN.baf": [],
    "Character/MANN/GESTIK/herranwinken_MANN.baf": [],
    "Character/MANN/GESTIK/jubeln_MANN.baf": [],
    "Character/MANN/GESTIK/kinn_kratzen_MANN.baf": [],
    "Character/MANN/GESTIK/klatschen_MANN.baf": [],
    "Character/MANN/GESTIK/kopf_kratzen_MANN.baf": [],
    "Character/MANN/GESTIK/kopf_nicken_MANN.baf": [],
    "Character/MANN/GESTIK/kopf_schraeg_links_MANN.baf": [],
    "Character/MANN/GESTIK/kopf_schraeg_rechts_MANN.baf": [],
    "Character/MANN/GESTIK/kopf_schuetteln_MANN.baf": [],
    "Character/MANN/GESTIK/manipulieren_hockend_MANN.baf": [],
    "Character/MANN/GESTIK/manipulieren_stehend_MANN.baf": [],
    "Character/MANN/GESTIK/mit_faust_droh_MANN.baf": [],
    "Character/MANN/GESTIK/nach_unten_sehen_MANN.baf": [],
    "Character/MANN/GESTIK/segnen_MANN.baf": [],
    "Character/MANN/GESTIK/steh_noise61_MANN.baf": [],
    "Character/MANN/GESTIK/steh_noise7_MANN.baf": [],
    "Character/MANN/GESTIK/steh_noise8_MANN.baf": [],
    "Character/MANN/GESTIK/steh_noise9_MANN.baf": [],
    "Character/MANN/GESTIK/tresen_wischen_MANN.baf": [],
    "Character/MANN/GESTIK/um_hand_anhalten_MANN.baf": [],
    "Character/MANN/GESTIK/verbeugen_MANN.baf": [],
    "Character/MANN/GESTIK/zeigen_MANN.baf": [],
    "Character/MANN/GESTIK/zum_mund_MANN.baf": [],
    "Character/MANN/KAMPF/arm_greifen_MANN.baf": [],
    "Character/MANN/KAMPF/aufrichten_MANN.baf": [],
    "Character/MANN/KAMPF/aufstehen_MANN.baf": [],
    "Character/MANN/KAMPF/ausweichen_hinten_MANN.baf": [],
    "Character/MANN/KAMPF/ausweichen_seite_MANN.baf": [],
    "Character/MANN/KAMPF/bauch_greifen_MANN.baf": [],
    "Character/MANN/KAMPF/boxen_MANN.baf": [],
    "Character/MANN/KAMPF/budspencerhieb_MANN.baf": [],
    "Character/MANN/KAMPF/ducken_MANN.baf": [],
    "Character/MANN/KAMPF/hieb_abwehr_MANN.baf": [],
    "Character/MANN/KAMPF/hieb_MANN.baf": [],
    "Character/MANN/KAMPF/priester_MANN.baf": [],
    "Character/MANN/KAMPF/schiessen_armbrust_MANN.baf": [],
    "Character/MANN/KAMPF/schiessen_pistole_MANN.baf": [],
    "Character/MANN/KAMPF/schlagen1_MANN.baf": [],
    "Character/MANN/KAMPF/schlagen2_MANN.baf": [],
    "Character/MANN/KAMPF/schlagen3_MANN.baf": [],
    "Character/MANN/KAMPF/schulter_anrempeln_MANN.baf": [],
    "Character/MANN/KAMPF/stechen_MANN.baf": [],
    "Character/MANN/KAMPF/sterben_MANN.baf": [],
    "Character/MANN/KAMPF/stich_abwehr_MANN.baf": [],
    "Character/MANN/KAMPF/stich_ausweichen_MANN.baf": [],
    "Character/MANN/KAMPF/stich_MANN.baf": [],
    "Character/MANN/KAMPF/streich_MANN.baf": [],
    "Character/MANN/KAMPF/taumeln_MANN.baf": [],
    "Character/MANN/KAMPF/todumfallen_MANN.baf": [],
    "Character/MANN/KAMPF/wegstossen_MANN.baf": [],
    "Character/MANN/KAMPF/werfen_MANN.baf": [],
    "Character/MANN/KAMPF/zu_boden_sinken_MANN.baf": [],
    "Character/MANN/Kritzelkratzel/handwerker2_MANN_am_tisch_schreiben.baf": [],
    "Character/MANN/Kritzelkratzel/handwerker2_MANN_einhand_vom_tisch.baf": [],
    "Character/MANN/Kritzelkratzel/handwerker2_MANN_hobeln.baf": [],
    "Character/MANN/Kritzelkratzel/handwerker2_MANN_saegen.baf": [],
    "Character/MANN/Kritzelkratzel/handwerker2_MANN_vom_boden_nehmen.baf": [],
    "Character/MANN/Kritzelkratzel/offizier_SOLDAT_schmieden.baf": [],
    "Character/MANN/Kritzelkratzel/offizier_SOLDAT_stich_ausweichen.baf": [],
    "Character/MANN/Kritzelkratzel/offizier_SOLDAT_werfen.baf": [],
    "Character/MANN/Kritzelkratzel/ratsherr2_KUTTE_predigen.baf": [],
    "Character/MANN/Kritzelkratzel/tischnehmen1_MANN.baf": [],
    "Character/MANN/SITZEND/aufstehen_MANN.baf": [],
    "Character/MANN/SITZEND/hinsetzen_MANN.baf": [],
    "Character/MANN/SITZEND/sitzgespreach2_MANN.baf": [],
    "Character/MANN/SITZEND/sitzgespreach3_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_ja_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_kopfdreh_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_kopfsenk_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_manipulieren_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_nein_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_newnoise_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_noise1_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_noise2_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_noise3_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_noise4_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_reden_aufgeregt_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_reden_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_schreiben_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_still_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_trinken_MANN.baf": [],
    "Character/MANN/SITZEND/sitz_umschau_MANN.baf": [],
    "Character/MANN/SPEZIAL/angeln_MANN.baf": [],
    "Character/MANN/SPEZIAL/auf_ruecken_schwing_MANN.baf": [],
    "Character/MANN/SPEZIAL/auf_tisch_legen_MANN.baf": [],
    "Character/MANN/SPEZIAL/auskippen_MANN.baf": [],
    "Character/MANN/SPEZIAL/einhaendig_vom_boden_nehmen_MANN.baf": [],
    "Character/MANN/SPEZIAL/einhand_vom_tisch_MANN.baf": [],
    "Character/MANN/SPEZIAL/fallenlassen_MANN.baf": [],
    "Character/MANN/SPEZIAL/gegenstand_schuetteln_MANN.baf": [],
    "Character/MANN/SPEZIAL/gegenstand_schuetteln_zweihaendig_MANN.baf": [],
    "Character/MANN/SPEZIAL/in_andere_hand_geben_MANN.baf": [],
    "Character/MANN/SPEZIAL/in_guertel_steck_MANN.baf": [],
    "Character/MANN/SPEZIAL/in_tasche_steck_MANN.baf": [],
    "Character/MANN/SPEZIAL/laterne_anzuenden_MANN.baf": [],
    "Character/MANN/SPEZIAL/meckern_MANN.baf": [],
    "Character/MANN/SPEZIAL/niederkniehen_ehre_MANN.baf": [],
    "Character/MANN/SPEZIAL/niederkniehen_tod_MANN.baf": [],
    "Character/MANN/SPEZIAL/runterbeug_sucht_MANN.baf": [],
    "Character/MANN/SPEZIAL/runterbeug_such_MANN.baf": [],
    "Character/MANN/SPEZIAL/Scheiterhaufen.baf": [],
    "Character/MANN/SPEZIAL/Scheiterhaufen_MANN.baf": [],
    "Character/MANN/SPEZIAL/singen_MANN.baf": [],
    "Character/MANN/SPEZIAL/wuerfel_MANN.baf": [],
    "Character/MANN/SPEZIAL/zweihand_vom_boden_aufnehmen_MANN.baf": [],
    "Character/MANN/SPEZIAL/zweihand_vom_tisch_MANN.baf": [],
    "Character/MANN/Stand_still_MANN.baf": [],
    "Character/MANN/Stand_still_MANN_BAK.baf": [],
    "Character/MANN/STEHEN/stehen_1_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_2_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_3_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_4_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_5_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_6a_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_6_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_7_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_8_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_9_MANN.baf": [],
    "Character/MANN/STEHEN/stehen_newnoise_MANN.baf": [],
    "Character/MANN/ZIRKUS/anfeuern_MANN.baf": [],
    "Character/MANN/ZIRKUS/handstand2_MANN.baf": [],
    "Character/MANN/ZIRKUS/handstand_MANN.baf": [],
    "Character/MANN/ZIRKUS/lachen_MANN.baf": [],
    "Character/MANN/ZIRKUS/lang_winken_MANN.baf": [],
    "Character/MANN/ZIRKUS/posieren_MANN.baf": [],
    "Character/MANN/ZIRKUS/ruecksalto2_MANN.baf": [],
    "Character/MANN/ZIRKUS/ruecksalto_MANN.baf": [],
    "Character/MANN/ZIRKUS/stehend_beschwoeren_MANN.baf": [],
    "Character/MANN/ZIRKUS/tief_verbeugen_MANN.baf": [],
    "Character/MANN2/abstimmung/sitzung1_MANN2.baf": [],
    "Character/MANN2/abstimmung/sitzung2_MANN2.baf": [],
    "Character/MANN2/abstimmung/sitzung3_MANN2.baf": [],
    "Character/MANN2/abstimmung/sitzung4_MANN2.baf": [],
    "Character/MANN2/abstimmung/sitzung5_MANN2.baf": [],
    "Character/MANN2/ARBEIT/am_tisch_schreiben_MANN2.baf": [],
    "Character/MANN2/ARBEIT/baumfaellen_MANN2.baf": [],
    "Character/MANN2/ARBEIT/hacken_MANN2.baf": [],
    "Character/MANN2/ARBEIT/hebel_ziehen_MANN2.baf": [],
    "Character/MANN2/ARBEIT/hobeln_MANN2.baf": [],
    "Character/MANN2/ARBEIT/meisseln_MANN2.baf": [],
    "Character/MANN2/ARBEIT/metall_erhitzen_MANN2.baf": [],
    "Character/MANN2/ARBEIT/mist_schaufeln_MANN2.baf": [],
    "Character/MANN2/ARBEIT/muenz_praegung_MANN2.baf": [],
    "Character/MANN2/ARBEIT/naehen_MANN2.baf": [],
    "Character/MANN2/ARBEIT/neufegen2_MANN2.baf": [],
    "Character/MANN2/ARBEIT/saegen_MANN2.baf": [],
    "Character/MANN2/ARBEIT/schmieden_MANN2.baf": [],
    "Character/MANN2/ARBEIT/schoepfen_MANN2.baf": [],
    "Character/MANN2/ARBEIT/schreiben_MANN2.baf": [],
    "Character/MANN2/ARBEIT/schweissab_MANN2.baf": [],
    "Character/MANN2/ARBEIT/seil_ziehen_MANN2.baf": [],
    "Character/MANN2/ARBEIT/umruehren_auftisch_MANN2.baf": [],
    "Character/MANN2/ARBEIT/umruehren_MANN2.baf": [],
    "Character/MANN2/ARBEIT/zapfen_MANN2.baf": [],
    "Character/MANN2/Bewegung/dreh_45_links_MANN2.baf": [],
    "Character/MANN2/Bewegung/dreh_45_rechts_MANN2.baf": [],
    "Character/MANN2/Bewegung/dreh_90_links_MANN2.baf": [],
    "Character/MANN2/Bewegung/dreh_90_rechts_MANN2.baf": [],
    "Character/MANN2/Bewegung/gebueckt_gehen_MANN2.baf": [],
    "Character/MANN2/Bewegung/gehen_MANN2.baf": [],
    "Character/MANN2/Bewegung/karren_ziehen_MANN2.baf": [],
    "Character/MANN2/Bewegung/leitersteigen_MANN2.baf": [],
    "Character/MANN2/Bewegung/springen_MANN2.baf": [],
    "Character/MANN2/Bewegung/step_MANN2.baf": [],
    "Character/MANN2/Bewegung/zu_boden_sinken_MANN2.baf": [],
    "Character/MANN2/GESTIK/abfaellig_MANN2.baf": [],
    "Character/MANN2/GESTIK/anpreisen_MANN2.baf": [],
    "Character/MANN2/GESTIK/armsehen_MANN2.baf": [],
    "Character/MANN2/GESTIK/bauch_reiben_MANN2.baf": [],
    "Character/MANN2/GESTIK/bein_kratzen_MANN2.baf": [],
    "Character/MANN2/GESTIK/beschwoeren_MANN2.baf": [],
    "Character/MANN2/GESTIK/durch_haar_fahr_MANN2.baf": [],
    "Character/MANN2/GESTIK/gespraech1_MANN2.baf": [],
    "Character/MANN2/GESTIK/gespraech5_MANN2.baf": [],
    "Character/MANN2/GESTIK/gespraech6_MANN2.baf": [],
    "Character/MANN2/GESTIK/haende_reiben_MANN2.baf": [],
    "Character/MANN2/GESTIK/herranwinken_MANN2.baf": [],
    "Character/MANN2/GESTIK/jubeln_MANN2.baf": [],
    "Character/MANN2/GESTIK/kinn_kratzen_MANN2.baf": [],
    "Character/MANN2/GESTIK/klatschen_MANN2.baf": [],
    "Character/MANN2/GESTIK/kopf_kratzen_MANN2.baf": [],
    "Character/MANN2/GESTIK/kopf_nicken_MANN2.baf": [],
    "Character/MANN2/GESTIK/kopf_schraeg_links_MANN2.baf": [],
    "Character/MANN2/GESTIK/kopf_schraeg_rechts_MANN2.baf": [],
    "Character/MANN2/GESTIK/kopf_schuetteln_MANN2.baf": [],
    "Character/MANN2/GESTIK/manipulieren_hockend_MANN2.baf": [],
    "Character/MANN2/GESTIK/manipulieren_stehend_MANN2.baf": [],
    "Character/MANN2/GESTIK/mit_faust_droh_MANN2.baf": [],
    "Character/MANN2/GESTIK/nach_unten_sehen_MANN2.baf": [],
    "Character/MANN2/GESTIK/segnen_MANN2.baf": [],
    "Character/MANN2/GESTIK/steh_noise61_MANN2.baf": [],
    "Character/MANN2/GESTIK/steh_noise7_MANN2.baf": [],
    "Character/MANN2/GESTIK/steh_noise8_MANN2.baf": [],
    "Character/MANN2/GESTIK/steh_noise9_MANN2.baf": [],
    "Character/MANN2/GESTIK/um_hand_anhalten_MANN2.baf": [],
    "Character/MANN2/GESTIK/verbeugen_MANN2.baf": [],
    "Character/MANN2/GESTIK/zeigen_MANN2.baf": [],
    "Character/MANN2/GESTIK/zum_mund_MAN2.baf": [],
    "Character/MANN2/GESTIK/zum_mund_MANN2.baf": [],
    "Character/MANN2/KAMPF/arm_greifen_MANN2.baf": [],
    "Character/MANN2/KAMPF/aufrichten_MANN2.baf": [],
    "Character/MANN2/KAMPF/aufstehen_MANN2.baf": [],
    "Character/MANN2/KAMPF/ausweichen_hinten_MANN2.baf": [],
    "Character/MANN2/KAMPF/ausweichen_seite_MANN2.baf": [],
    "Character/MANN2/KAMPF/bauch_greifen_MANN2.baf": [],
    "Character/MANN2/KAMPF/boxen_MANN2.baf": [],
    "Character/MANN2/KAMPF/budspencerhieb_MANN2.baf": [],
    "Character/MANN2/KAMPF/ducken_MANN2.baf": [],
    "Character/MANN2/KAMPF/hieb_abwehr_MANN2.baf": [],
    "Character/MANN2/KAMPF/hieb_MANN2.baf": [],
    "Character/MANN2/KAMPF/priester_MANN2.baf": [],
    "Character/MANN2/KAMPF/schiessen_armbrust_MANN2.baf": [],
    "Character/MANN2/KAMPF/schiessen_pistole_MANN2.baf": [],
    "Character/MANN2/KAMPF/schlagen1_MANN2.baf": [],
    "Character/MANN2/KAMPF/schlagen2_MANN2.baf": [],
    "Character/MANN2/KAMPF/schlagen3_MANN2.baf": [],
    "Character/MANN2/KAMPF/schulter_anrempeln_MANN2.baf": [],
    "Character/MANN2/KAMPF/stechen_MANN2.baf": [],
    "Character/MANN2/KAMPF/sterben_MANN2.baf": [],
    "Character/MANN2/KAMPF/stich_abwehr_MANN2.baf": [],
    "Character/MANN2/KAMPF/stich_ausweichen_MANN2.baf": [],
    "Character/MANN2/KAMPF/stich_MANN2.baf": [],
    "Character/MANN2/KAMPF/streich_MANN2.baf": [],
    "Character/MANN2/KAMPF/taumeln_MANN2.baf": [],
    "Character/MANN2/KAMPF/todumfallen_MANN2.baf": [],
    "Character/MANN2/KAMPF/wegstossen_MANN2.baf": [],
    "Character/MANN2/KAMPF/werfen_MANN2.baf": [],
    "Character/MANN2/KAMPF/zu_boden_sinken_MANN2.baf": [],
    "Character/MANN2/NEU/linksdrehen45_MANN.baf": [],
    "Character/MANN2/NEU/linksdrehen90_MANN.baf": [],
    "Character/MANN2/NEU/rechtsdrehen45_MANN.baf": [],
    "Character/MANN2/NEU/rechtsdrehen90_MANN.baf": [],
    "Character/MANN2/NEU/schritt_MANN.baf": [],
    "Character/MANN2/SITZEND/aufstehen_MANN2.baf": [],
    "Character/MANN2/SITZEND/hinsetzen_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_ja_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_kopfdreh_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_kopfsenk_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_manipulieren_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_nein_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_newnoise_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_noise1_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_noise2_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_noise3_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_noise4_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_reden_aufgeregt_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_reden_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_schreiben_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_still_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_trinken_MANN2.baf": [],
    "Character/MANN2/SITZEND/sitz_umschau_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/auf_ruecken_schwing_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/auf_tisch_legen_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/auskippen_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/einhaendig_vom_boden_nehmen_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/einhand_vom_tisch_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/fallenlassen_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/gegenstand_schuetteln_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/gegenstand_schuetteln_zweihaendig_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/in_andere_hand_geben_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/in_guertel_steck_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/in_tasche_steck_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/laterne_anzuenden_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/meckern_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/niederkniehen_ehre_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/niederkniehen_tod_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/runterbeug_sucht_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/runterbeug_such_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/scheiterhaufen_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/singen_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/wuerfel_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/zweihand_vom_boden_aufnehmen_MANN2.baf": [],
    "Character/MANN2/SPEZIAL/zweihand_vom_tisch_MANN2.baf": [],
    "Character/MANN2/Stand_still_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_1_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_2_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_3_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_4_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_5_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_6a_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_6_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_7_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_8_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_9_MANN2.baf": [],
    "Character/MANN2/STEHEN/stehen_newnoise_MANN2.baf": [],
    "Character/MANN3/Abstimmung/sitzung1_MANN3.baf": [],
    "Character/MANN3/Abstimmung/sitzung2_MANN3.baf": [],
    "Character/MANN3/Abstimmung/sitzung3_MANN3.baf": [],
    "Character/MANN3/Abstimmung/sitzung4_MANN3.baf": [],
    "Character/MANN3/Abstimmung/sitzung5_MANN3.baf": [],
    "Character/MANN3/Bewegung/dreh_45_links_MANN3.baf": [],
    "Character/MANN3/Bewegung/dreh_45_rechts_MANN3.baf": [],
    "Character/MANN3/Bewegung/dreh_90_links_MANN3.baf": [],
    "Character/MANN3/Bewegung/dreh_90_rechts_MANN3.baf": [],
    "Character/MANN3/Bewegung/gehen_MANN3.baf": [],
    "Character/MANN3/Bewegung/stehen_newnoise_MANN3.baf": [],
    "Character/MANN3/Gestik/abfaellig_MANN3.baf": [],
    "Character/MANN3/Gestik/bauch_reiben_MANN3.baf": [],
    "Character/MANN3/Gestik/bein_kratzen_MANN3.baf": [],
    "Character/MANN3/Gestik/durch_haar_fahr_MANN3.baf": [],
    "Character/MANN3/Gestik/gespraech1_MANN3.baf": [],
    "Character/MANN3/Gestik/gespraech5_MANN3.baf": [],
    "Character/MANN3/Gestik/haende_reiben_MANN3.baf": [],
    "Character/MANN3/Gestik/kinn_kratzen_MANN3.baf": [],
    "Character/MANN3/Gestik/kopf_nicken_MANN3.baf": [],
    "Character/MANN3/Gestik/kopf_schraeg_rechts_MANN3.baf": [],
    "Character/MANN3/Gestik/kopf_schuetteln_MANN3.baf": [],
    "Character/MANN3/Gestik/mit_faust_droh_MANN3.baf": [],
    "Character/MANN3/Gestik/nach_unten_sehen_MANN3.baf": [],
    "Character/MANN3/Gestik/steh_noise7_MANN3.baf": [],
    "Character/MANN3/Gestik/steh_noise8_MANN3.baf": [],
    "Character/MANN3/Gestik/steh_noise9_MANN3.baf": [],
    "Character/MANN3/Kampf/schiessen_pistole_MANN3.baf": [],
    "Character/MANN3/Kampf/stich_ausweichen_MANN3.baf": [],
    "Character/MANN3/Kampf/taumeln_MANN3.baf": [],
    "Character/MANN3/sitzend/hinsetzen_MANN3.baf": [],
    "Character/MANN3/sitzend/sitzgespraech2_MANN3.baf": [],
    "Character/MANN3/sitzend/sitzgespraech3_MANN3.baf": [],
    "Character/MANN3/sitzend/sitz_ja_MANN3.baf": [],
    "Character/MANN3/sitzend/sitz_kopfsenk_MANN3.baf": [],
    "Character/MANN3/sitzend/sitz_nein_MANN3.baf": [],
    "Character/MANN3/sitzend/sitz_newnoise_MANN3.baf": [],
    "Character/MANN3/sitzend/sitz_noise1_MANN3.baf": [],
    "Character/MANN3/sitzend/sitz_reden_MANN3.baf": [],
    "Character/MANN3/Spezial/scheiterhaufen_MANN3.baf": [],
    "Character/MANN3/Stehen/stehen_newnoise_MANN3.baf": [],
    "Character/medium/Bewegung/dreh_45_links_MEDIUM.baf": [],
    "Character/medium/Bewegung/dreh_45_rechts_MEDIUM.baf": [],
    "Character/medium/Bewegung/dreh_90_links_MEDIUM.baf": [],
    "Character/medium/Bewegung/dreh_90_rechts_MEDIUM.baf": [],
    "Character/medium/Bewegung/gehen_MEDIUM.baf": [],
    "Character/medium/Bewegung/karren_ziehen_MEDIUM.baf": [],
    "Character/medium/STEHEN/stehen_newnoise_MEDIUM.baf": [],
    "Character/MEISTER/Abstimmung/sitzung1_MEISTER.baf": [],
    "Character/MEISTER/Abstimmung/sitzung2_MEISTER.baf": [],
    "Character/MEISTER/Abstimmung/sitzung3_MEISTER.baf": [],
    "Character/MEISTER/Abstimmung/sitzung4_MEISTER.baf": [],
    "Character/MEISTER/Abstimmung/sitzung5_MEISTER.baf": [],
    "Character/MEISTER/Bewegung/dreh_45_links_MEISTER.baf": [],
    "Character/MEISTER/Bewegung/dreh_45_rechts_MEISTER.baf": [],
    "Character/MEISTER/Bewegung/dreh_90_links_MEISTER.baf": [],
    "Character/MEISTER/Bewegung/dreh_90_rechts_MEISTER.baf": [],
    "Character/MEISTER/Bewegung/gehen_MEISTER.baf": [],
    "Character/MEISTER/Gestik/abfaellig_MEISTER.baf": [],
    "Character/MEISTER/Gestik/bauch_reiben_MEISTER.baf": [],
    "Character/MEISTER/Gestik/beschwoeren_MEISTER.baf": [],
    "Character/MEISTER/Gestik/durch_haar_fahr_MEISTER.baf": [],
    "Character/MEISTER/Gestik/gespraech1_MEISTER.baf": [],
    "Character/MEISTER/Gestik/gespraech5_MEISTER.baf": [],
    "Character/MEISTER/Gestik/gespraech6_MEISTER.baf": [],
    "Character/MEISTER/Gestik/haende_reiben_MEISTER.baf": [],
    "Character/MEISTER/Gestik/kinn_kratzen_MEISTER.baf": [],
    "Character/MEISTER/Gestik/kopf_nicken_MEISTER.baf": [],
    "Character/MEISTER/Gestik/kopf_schuetteln_MEISTER.baf": [],
    "Character/MEISTER/Gestik/mit_faust_droh_MEISTER.baf": [],
    "Character/MEISTER/Gestik/nach_unten_sehen_MEISTER.baf": [],
    "Character/MEISTER/Gestik/stehen_noise61_MEISTER.baf": [],
    "Character/MEISTER/Gestik/steh_noise7_MEISTER.baf": [],
    "Character/MEISTER/Gestik/steh_noise8_MEISTER.baf": [],
    "Character/MEISTER/Gestik/steh_noise9_MEISTER.baf": [],
    "Character/MEISTER/Kampf/schiessen_pistole_MEISTER.baf": [],
    "Character/MEISTER/Kampf/stich_ausweichen_MEISTER.baf": [],
    "Character/MEISTER/Kampf/taumeln_MEISTER.baf": [],
    "Character/MEISTER/sitzend/hinsetzen_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitzgespraech2_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitzgespraech3_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitz_ja_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitz_kopfsenk_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitz_nein_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitz_newnoise_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitz_noise1_MEISTER.baf": [],
    "Character/MEISTER/sitzend/sitz_reden_MEISTER.baf": [],
    "Character/MEISTER/Spezial/niederkniehen_tod_MEISTER.baf": [],
    "Character/MEISTER/Spezial/scheiterhaufen_MEISTER.baf": [],
    "Character/MEISTER/STEHEN/stehen_newnoise_MEISTER.baf": [],
    "Character/MUTTER_BETT/mutter_bett.baf": [],
    "Character/Pferd/Bewegung/fressen_PFERD.baf": [],
    "Character/Pferd/Bewegung/galopp_PFERD.baf": [],
    "Character/Pferd/Bewegung/gehen_PFERD.baf": [],
    "Character/Pferd/Bewegung/karren_ziehen_PFERD.baf": [],
    "Character/Pferd/Bewegung/stehen_PFERD.baf": [],
    "Character/Pferd/Bewegung/traben_PFERD.baf": [],
    "Character/Pferd/Bewegung/wiehern_PFERD.baf": [],
    "Character/Rabe/kraehen_RABE.baf": [],
    "Character/Rabe/umschauen_RABE.baf": [],
    "Character/Rabe/warten_RABE.baf": [],
    "Character/Ratte/Bewegung/fressen_RATTE.baf": [],
    "Character/Ratte/Bewegung/gehen_RATTE.baf": [],
    "Character/Ratte/Bewegung/stehen_RATTE.baf": [],
    "Character/Schaf/Bewegung/fressen_SCHAF.baf": [],
    "Character/Schaf/Bewegung/gehen_SCHAF.baf": [],
    "Character/Schaf/Bewegung/stehen_SCHAF.baf": [],
    "Character/Schwein/Bewegung/drehen_SCHWEIN.baf": [],
    "Character/Schwein/Bewegung/fressen_SCHWEIN.baf": [],
    "Character/Schwein/Bewegung/gehen_SCHWEIN.baf": [],
    "Character/Schwein/Bewegung/stehen_SCHWEIN.baf": [],
    "Character/sensenmann/sensenmann.baf": [],
    "Character/SOLDAT/abstimmung/sitzung1_SOLDAT.baf": [],
    "Character/SOLDAT/abstimmung/sitzung2_SOLDAT.baf": [],
    "Character/SOLDAT/abstimmung/sitzung3_SOLDAT.baf": [],
    "Character/SOLDAT/abstimmung/sitzung4_SOLDAT.baf": [],
    "Character/SOLDAT/abstimmung/sitzung5_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/am_tisch_schreiben_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/baumfaellen_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/hacken_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/hebel_ziehen_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/hobeln_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/meisseln_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/metall_erhitzen_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/mist_schaufeln_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/muenz_praegung_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/naehen_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/neufegen2_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/saegen_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/schmieden_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/schoepfen_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/schreiben_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/schweissab_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/seil_ziehen_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/umruehren_auftisch_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/umruehren_SOLDAT.baf": [],
    "Character/SOLDAT/ARBEIT/zapfen_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/dreh_45_links_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/dreh_45_rechts_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/dreh_90_links_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/dreh_90_rechts_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/gebueckt_gehen_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/gehen_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/karren_ziehen_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/leitersteigen_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/springen_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/step_SOLDAT.baf": [],
    "Character/SOLDAT/Bewegung/zu_boden_sinken_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/abfaellig_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/anpreisen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/armsehen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/bauch_reiben_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/bein_kratzen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/beschwoeren_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/durch_haar_fahr_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/gespraech1_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/gespraech5_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/gespraech6_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/haende_reiben_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/herranwinken_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/jubeln_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/kinn_kratzen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/klatschen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/kopf_kratzen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/kopf_nicken_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/kopf_schraeg_links_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/kopf_schraeg_rechts_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/kopf_schuetteln_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/manipulieren_hockend_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/manipulieren_stehend_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/mit_faust_droh_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/nach_unten_sehen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/segnen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/steh_noise61_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/steh_noise7_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/steh_noise8_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/steh_noise9_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/um_hand_anhalten_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/verbeugen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/zeigen_SOLDAT.baf": [],
    "Character/SOLDAT/GESTIK/zum_mund_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/arm_greifen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/aufrichten_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/aufstehen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/ausweichen_hinten_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/ausweichen_seite_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/bauch_greifen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/boxen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/budspencerhieb_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/ducken_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/hieb_abwehr_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/hieb_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/priester_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/schiessen_armbrust_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/schiessen_pistole_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/schlagen1_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/schlagen2_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/schlagen3_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/schulter_anrempeln_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/stechen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/sterben_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/stich_abwehr_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/stich_ausweichen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/stich_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/streich_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/taumeln_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/todumfallen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/wegstossen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/werfen2_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/werfen_SOLDAT.baf": [],
    "Character/SOLDAT/Kampf/zu_boden_sinken_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/aufstehen_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/hinsetzen_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzend_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzgespraech1_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzgespraech2_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzgespraech3_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzgespraech4_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzgespraech5_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzgespraech6_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitzgespraech7_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_greifen_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_ja_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_kopfdreh_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_kopfsenk_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_manipulieren_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_nein_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_newnoise_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise1_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise2_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise3_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise4_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise5_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise6_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise7_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_noise8_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_reden_aufgeregt_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_reden_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_schreiben_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_still_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_trinken_SOLDAT.baf": [],
    "Character/SOLDAT/SITZEND/sitz_umschau_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/auf_ruecken_schwing_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/auf_tisch_legen_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/auskippen_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/einhaendig_vom_boden_nehmen_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/einhand_vom_tisch_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/fallenlassen_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/gegenstand_schuetteln_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/gegenstand_schuetteln_zweihaendig_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/in_andere_hand_geben_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/in_guertel_steck_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/in_tasche_steck_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/laterne_anzuenden_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/meckern_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/niederkniehen_ehre_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/niederkniehen_tod_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/runterbeug_sucht_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/runterbeug_such_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/scheiterhaufen_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/singen_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/wuerfel_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/zweihand_vom_boden_aufnehmen_SOLDAT.baf": [],
    "Character/SOLDAT/SPEZIAL/zweihand_vom_tisch_SOLDAT.baf": [],
    "Character/SOLDAT/Stand_still_SOLDAT.baf": [],
    "Character/SOLDAT/STEHEN/stehen_newnoise_KUTTE.baf": [],
    "Character/SOLDAT/STEHEN/stehen_newnoise_SOLDAT.baf": [],
    "LowPolyCharacter/Dicker/gehen_DICKER_LOW.baf": [],
    "LowPolyCharacter/Dicker/karrenziehen_DICKER_LOW.baf": [],
    "LowPolyCharacter/Dicker/stehen_DICKER_LOW.baf": [],
    "LowPolyCharacter/Frau/gehen_FRAU_LOW.baf": [],
    "LowPolyCharacter/Frau/karrenziehen_FRAU_LOW.baf": [],
    "LowPolyCharacter/Frau/stehen_FRAU_LOW.baf": [],
    "LowPolyCharacter/Junge/gehen_JUNGE_LOW.baf": [],
    "LowPolyCharacter/Junge/karrenziehen_JUNGE_LOW.baf": [],
    "LowPolyCharacter/Junge/stehen_JUNGE_LOW.baf": [],
    "LowPolyCharacter/Kutte/gehen_KUTTE_LOW.baf": [],
    "LowPolyCharacter/Kutte/karrenziehen_KUTTE_LOW.baf": [],
    "LowPolyCharacter/Kutte/stehen_KUTTE_LOW.baf": [],
    "LowPolyCharacter/Maedchen/gehen_MAEDCHEN_LOW.baf": [],
    "LowPolyCharacter/Maedchen/karrenziehen_MAEDCHEN_LOW.baf": [],
    "LowPolyCharacter/Maedchen/stehen_MAEDCHEN_LOW.baf": [],
    "LowPolyCharacter/Mann/gehen_MANN_LOW.baf": [],
    "LowPolyCharacter/Mann/karrenziehen_MANN_LOW.baf": [],
    "LowPolyCharacter/Mann/stehen_MANN_LOW.baf": [],
    "LowPolyCharacter/Mann2/gehen_MANN2_LOW.baf": [],
    "LowPolyCharacter/Mann2/karrenziehen_MANN2_LOW.baf": [],
    "LowPolyCharacter/Mann2/stehen_MANN2_LOW.baf": [],
    "LowPolyCharacter/Soldat/gehen_SOLDAT_LOW.baf": [],
    "LowPolyCharacter/Soldat/karrenziehen_SOLDAT_LOW.baf": [],
    "LowPolyCharacter/Soldat/stehen_SOLDAT_LOW.baf": [],
    "Sonstiges/anim_FLUCHTFLAGGE.baf": [],
    "Sonstiges/anim_skelett.baf": [],
    "Sonstiges/diebesgilde_ILLUSIONSWAND_auf.baf": [],
    "Sonstiges/diebesgilde_ILLUSIONSWAND_zu.baf": [],
    "Sonstiges/diebesgilde_VORHANG.baf": [],
    "Sonstiges/ob_ARMBRUST_hnd.baf": [],
    "Sonstiges/ob_SCHRAUBPRESSE_PARFUMERIE.baf": [],
    "Sonstiges/sp_WIMPEL.baf": [],
    "Sonstiges/STADTPUNKT_ANM_K.baf": [],
    "Sonstiges/Stadtturm_Anm_K.baf": [],
    "Sonstiges/ub_Blutlache.baf": [],
    "Sonstiges/ub_FLAGGENMAST.baf": [],
    "Sonstiges/WAAGE_PARFUMERIE_eins.baf": [],
    "Sonstiges/Wimpel_Stadtturm.baf": [],
    "Sonstiges/Wimpel_Stadtturm_K-V.baf": [],
    "Sonstiges/Wimpel_Stadtturm_K.baf": [],
    "Sonstiges/windmuehle.baf": [],
    "Vogel/vogel_TAUBE.baf": [],
    "_ADDON/AO_Kanone_Wimpel_Aa.baf": [],
    "_ADDON/AO_Mech_Geist_Aa.baf": [],
    "_ADDON/AO_WIMPEL_ZIRKUSZELT.baf": [],
}
